[package]
name = "homie5"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4.30", features = ["serde"] }
regex = { version = "1.9.5", default-features = true }
thiserror = "1.0.49"
log = "0.4.20"

[dev-dependencies]
rumqttc = "0.24.0"
futures = "0.3.28"
bytes = "1.5.0"
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0.75"
ctrlc = "3.1"
log = "0.4"
env_logger = "0.9"

